# build with something like
#docker image build . -t rdptest
# d
# instantiate with something like docker container run -it rdptest:latest /bin/ash
# remove: docker rmi name
# list: docker images

FROM alpine:latest

RUN mkdir /apps


